global:
  scrape_interval: 10s
scrape_configs:
  - job_name: immich
    static_configs:
      - targets:
        - ix-immich-server-1:8082
  - job_name: immich-exporter
    static_configs:
      - targets:
        - immich-exporter:3000
  - job_name: jellyfin-exporter
    static_configs:
      - targets:
        - jellyfin-exporter:9027
  - job_name: pihole-exporter
    static_configs:
      - targets:
        - pihole-exporter:9617
  - job_name: qbittorrent-exporter
    static_configs:
      - targets:
        - qbittorrent-exporter:8000
  - job_name: scraparr-exporter
    static_configs:
      - targets:
        - scraparr-exporter:7100
  - job_name: graphite-exporter
    static_configs:
      - targets:
        - graphite-exporter:9108
